project='.| One point left'
description='.| One point left, activate all robots 0.1.0'
full_description='The documentation is available @{README.md|here}.'
title='.| One point left Documentation'
dir='./doc/api'
style='!fixed'
use_markdown_titles = true
format='discount'
sort_modules=true
file={'./src', exclude = {'src/assets/libs'}}
kind_names={topic='Manual',module='Libraries'}
readme='README.md'
style='./doc/api/'
